"""Guard over the committed reviewer evidence tree (docs/spec.md 1.1 item 6, 9, 16.2).

The files under ``evidence/`` are regenerated by the README demo commands, not by tests, so
nothing else re-checks them. This module fails the suite if a regeneration ever brings back a
wall-clock field (see ``tests/wallclock.py``) or persists one of the raw synthetic sensitive
values that only runtime memory may hold. It reads the committed tree and never writes to it.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from tests.wallclock import EVIDENCE_SUFFIXES, assert_no_wall_clock, wall_clock_violations

EVIDENCE_DIR = Path(__file__).resolve().parents[2] / "evidence"
CAPABILITY_DIR = EVIDENCE_DIR / "mockbank" / "lookup_member_balance"

# spec 16.2 layout: run directory -> files every regeneration must produce
RUN_FILES: dict[str, set[str]] = {
    "discovery": {"meta.json", "events.jsonl", "artifact.json"},
    "replay-success": {"meta.json", "events.jsonl", "result.json"},
    "replay-notfound": {"meta.json", "events.jsonl", "result.json"},
    "replay-interstitial": {"meta.json", "events.jsonl", "result.json"},
    "replay-hitl": {"meta.json", "events.jsonl", "intervention.json", "human-events.jsonl", "result.json", "masked.png"},
}

# raw runtime forms of the synthetic MockBank data (mockbank.app.MEMBERS): the demo member id,
# its savings balance in every form the money parser and the page use, and the second member
# a human may navigate to during the HITL run.
RAW_SENSITIVE_LITERALS = ("12345", "1,234.56", "1234.56", "24680", "88.20")


def committed_files() -> list[Path]:
    files = sorted(p for p in EVIDENCE_DIR.rglob("*") if p.is_file())
    assert files, f"no committed evidence under {EVIDENCE_DIR}"
    return files


def test_committed_evidence_layout_is_complete() -> None:
    for run, expected in RUN_FILES.items():
        present = {p.name for p in (CAPABILITY_DIR / run).glob("*")}
        assert expected <= present, f"{run}/ is missing {sorted(expected - present)}"


@pytest.mark.parametrize("run", sorted(RUN_FILES))
def test_committed_evidence_carries_no_wall_clock_fields(run: str) -> None:
    expected = {name for name in RUN_FILES[run] if Path(name).suffix in EVIDENCE_SUFFIXES}
    assert_no_wall_clock(CAPABILITY_DIR / run, expected)


def test_every_committed_json_file_is_covered_by_the_wall_clock_scan() -> None:
    """The per-run scan above must not silently skip a file added outside the known layout."""
    scanned = {p for run in RUN_FILES for p in (CAPABILITY_DIR / run).rglob("*") if p.suffix in EVIDENCE_SUFFIXES}
    all_json = {p for p in committed_files() if p.suffix in EVIDENCE_SUFFIXES}
    stray = sorted(p.relative_to(EVIDENCE_DIR).as_posix() for p in all_json - scanned)
    assert not stray, f"evidence files outside the spec 16.2 layout: {stray}"
    for path in sorted(all_json):
        assert not wall_clock_violations(path), path


def test_committed_evidence_contains_no_raw_sensitive_literal() -> None:
    """Scans every committed byte and every relative path (spec 4.1: no sensitive value in filenames)."""
    leaks: list[str] = []
    for path in committed_files():
        relative = path.relative_to(EVIDENCE_DIR).as_posix()
        payload = path.read_bytes()
        for literal in RAW_SENSITIVE_LITERALS:
            if literal in relative:
                leaks.append(f"{relative}: path contains {literal!r}")
            if literal.encode("ascii") in payload:
                leaks.append(f"{relative}: content contains {literal!r}")
    assert not leaks, "committed evidence leaks a raw sensitive literal:\n" + "\n".join(leaks)
